import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {shellTool,preflightTool,ToolPreconditionError,validateTool,writeTool} from '../src/tools.mjs';
test('malformed browser calls fail before opening a browser or requesting command review',()=>{assert.throws(()=>validateTool({name:'shell',arguments:{program:'tom-browser',args:['--bogus','localStorage guide']}}),/Invalid browser arguments/);assert.throws(()=>validateTool({name:'shell',arguments:{program:'tom-browser',args:['--action','read']}}),/needs --url/);const a=validateTool({name:'shell',arguments:{program:'tom-browser',args:['--action','search','--query','localStorage MDN','--provider','bing']}});assert.equal(a.arguments.args[3],'localStorage MDN');});
test('write repair reports the missing field and retains destination hash protection',()=>{assert.throws(()=>validateTool({name:'write',arguments:{content:'page',expectedHash:'new'}}),/Missing or invalid path/);assert.throws(()=>validateTool({name:'write',arguments:{path:'page.html',expectedHash:'new'}}),/Missing or invalid content/);assert.throws(()=>validateTool({name:'write',arguments:{path:'page.html',content:'page',expectedHash:'[omitted]'}}),/Placeholder strings are invalid/);});
test('blank optional hash permits creation but cannot overwrite an existing file',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tom-blank-'));try{const action=validateTool({name:'write',arguments:{summary:'Create a note',path:'note.txt',content:'first',expectedHash:''}});assert.equal(action.arguments.expectedHash,'new');await writeTool(action.arguments,dir,path.join(dir,'snapshots'));await assert.rejects(writeTool({...action.arguments,content:'second'},dir,path.join(dir,'snapshots')),ToolPreconditionError);assert.equal(await fs.readFile(path.join(dir,'note.txt'),'utf8'),'first');}finally{await fs.rm(dir,{recursive:true});}});
test('portable cat reads literal Unicode paths without an installed Unix shell',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'tom-read-'));try{await fs.writeFile(path.join(dir,'café notes.txt'),'CEDAR-17');const r=await shellTool({program:'cat',args:['café notes.txt']},dir);assert.equal(r.exitCode,0);assert.equal(r.output,'CEDAR-17');}finally{await fs.rm(dir,{recursive:true});}});
test('a missing executable is a precondition failure, not an uncertain side effect',async()=>{await assert.rejects(shellTool({program:'tom-missing-executable-438293.exe',args:[]},process.cwd()),ToolPreconditionError);});
test('a single PowerShell cmdlet argument is made explicit without changing its command',()=>{const command="Get-Content -LiteralPath 'café notes.txt'";const a=validateTool({name:'shell',arguments:{program:'powershell.exe',args:[command]}});assert.deepEqual(a.arguments.args,['-NoProfile','-NonInteractive','-Command',command]);assert.equal(a.summarySource,'harness');assert.throws(()=>validateTool({name:'shell',arguments:{program:'powershell.exe',args:['notes.txt']}}),/explicit -Command/);});
test('PowerShell parsing catches an unterminated quote without executing the command',{skip:process.platform!=='win32'},async()=>{await assert.rejects(preflightTool({name:'shell',arguments:{program:'powershell.exe',args:['-NoProfile','-Command',"Write-Output 'unclosed"]}}),/syntax check failed/);await preflightTool({name:'shell',arguments:{program:'powershell.exe',args:['-NoProfile','-Command',"throw 'This statement must only be parsed'"]}});});

test('browser shorthand expands to explicit read-only arguments with selected provider recorded',()=>{const search=validateTool({name:'shell',arguments:{program:'tom-browser',args:['MDN localStorage']}},{browser:'edge',search:'bing'});assert.deepEqual(search.arguments.args,['--action','search','--query','MDN localStorage','--provider','bing','--browser','edge']);assert.deepEqual(search.normalization.requested,['MDN localStorage']);const read=validateTool({name:'shell',arguments:{program:'tom-browser',args:['https://developer.mozilla.org/']}});assert.equal(read.arguments.args[1],'read');});
