CREATE TABLE IF NOT EXISTS counters (name TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS snapshots (name TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS clone_days (day TEXT PRIMARY KEY, count INTEGER NOT NULL, uniques INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS refresh_locks (name TEXT PRIMARY KEY, attempted_at INTEGER NOT NULL);
